name: isite.com
favicon: null
layout_spectrum: 0.7532310707028955
typography_spectrum: 0.6241680120583624
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8258471589069813
  lightness: 0.9980772857088596
  saturation: 0.28746769577264786
  rhythmicContrast: 0.1842844500206411
purpose: []
